// projects/hunting-website/components/Footer.tsx
'use client'

import Image from 'next/image'
import Link from 'next/link'
import { usePathname } from 'next/navigation'

export default function Footer() {
  const pathname = usePathname()

  // Hide footer on studio page
  if (pathname.startsWith('/studio')) {
    return null
  }
  return (
    <footer className="bg-gray-900 text-white py-12">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8 text-center">
          <div className="flex flex-col items-center">
            <h4 className="text-lg font-semibold mb-4">Demo Hunting Club</h4>
            <p className="text-gray-400">
              Din arena for jakt, trening og fellesskap.
            </p>
          </div>
          <div className="flex flex-col items-center">
            <h4 className="text-lg font-semibold mb-4">Kontakt</h4>
            <ul className="space-y-2 text-gray-400">
              <li>
                <a href="mailto:info@demo-club.example" className="hover:text-white transition">
                  E-post: info@demo-club.example
                </a>
              </li>
              <li>Org.nr: XXX XXX XXX</li>
              <li>
                <a
                  href="#"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="hover:text-white transition"
                >
                  Demo Street 1, 0000 Demo City
                </a>
              </li>
            </ul>
          </div>
          <div className="flex flex-col items-center">
            <h4 className="text-lg font-semibold mb-4">Følg oss</h4>
            <div className="flex flex-col gap-3">
              <a href="https://www.facebook.com/" target="_blank" rel="noopener noreferrer" className="text-gray-400 hover:text-white transition flex items-center justify-center gap-2">
                <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
                </svg>
                <span>Facebook</span>
              </a>
              <a href="/studio" className="text-gray-400 hover:text-white transition flex items-center justify-center" aria-label="Admin">
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1" />
                </svg>
              </a>
            </div>
          </div>
        </div>
        <div className="border-t border-gray-800 pt-8 text-center text-gray-400">
          <p>&copy; {new Date().getFullYear()} Demo Hunting Club. Alle rettigheter reservert.</p>
        </div>
      </div>
    </footer>
  )
}

// projects/it-hjelperen/src/lib/components/Footer.svelte
<script lang="ts">
	import { CONTACT_PHONE, CONTACT_PHONE_DISPLAY, EMAIL_ADRESS } from '$lib/utils/constants';

	const currentYear = new Date().getFullYear();
</script>

<footer class="bg-gray-900 dark:bg-gray-950 text-gray-300 dark:text-gray-400 transition-colors duration-300">
	<div class="container-custom py-8">
		<div class="grid grid-cols-1 md:grid-cols-2 max-w-4xl mx-auto">
			<!-- Company Info -->
			<div>
				<a href="/" class="inline-flex items-center mb-3" aria-label="IT Hjelperen hjem">
					<img
						src="/img/itvaktmesteren-logo.png"
						alt="IT Hjelperen logo"
						class="h-14 w-auto"
						loading="lazy"
						decoding="async"
					/>
				</a>
				<p class="text-sm mb-4">
					PC-bygging, reparasjon og IT-hjelp for privatpersoner og små bedrifter i Tromsø. <br>Vi tar oss av alt det tekniske!
				</p>
			</div>

			<!-- Contact Info -->
			<div class="md:ml-auto">
				<h3 class="text-white dark:text-gray-100 text-lg font-bold mb-3 transition-colors duration-300">Kontakt oss</h3>
				<ul class="space-y-2 text-sm">
					<li class="flex items-center">
						<svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
						</svg>
						<a href="tel:{CONTACT_PHONE}" class="hover:text-white dark:hover:text-gray-200 transition-colors duration-300">{CONTACT_PHONE_DISPLAY}</a>
					</li>
					<li class="flex items-center">
						<svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
						</svg>
						<a href="mailto:{EMAIL_ADRESS}" class="hover:text-white dark:hover:text-gray-200 transition-colors duration-300">{EMAIL_ADRESS}</a>
					</li>
				</ul>
			</div>
		</div>

		<!-- Bottom Bar -->
		<div class="border-t border-gray-800 dark:border-gray-900 mt-6 pt-4 text-sm text-center transition-colors duration-300">
			<p><a class="hover:text-white dark:hover-text-gray-200 transtition-colors duration-300" href="/">&copy; {currentYear} IT Hjelperen.</a> Alle rettigheter reservert.</p>
		</div>
	</div>
</footer>
