// projects/it-hjelperen/src/lib/components/Footer.svelte
<script lang="ts">
	import { CONTACT_PHONE, CONTACT_PHONE_DISPLAY, EMAIL_ADRESS } from '$lib/utils/constants';

	const currentYear = new Date().getFullYear();
</script>

<footer class="bg-gray-900 dark:bg-gray-950 text-gray-300 dark:text-gray-400 transition-colors duration-300">
	<div class="container-custom py-8">
		<div class="grid grid-cols-1 md:grid-cols-2 max-w-4xl mx-auto">
			<!-- Company Info -->
			<div>
				<a href="/" class="inline-flex items-center mb-3" aria-label="IT Hjelperen hjem">
					<img
						src="/img/itvaktmesteren-logo.png"
						alt="IT Hjelperen logo"
						class="h-14 w-auto"
						loading="lazy"
						decoding="async"
					/>
				</a>
				<p class="text-sm mb-4">
					PC-bygging, reparasjon og IT-hjelp for privatpersoner og små bedrifter i Tromsø. <br>Vi tar oss av alt det tekniske!
				</p>
			</div>

			<!-- Contact Info -->
			<div class="md:ml-auto">
				<h3 class="text-white dark:text-gray-100 text-lg font-bold mb-3 transition-colors duration-300">Kontakt oss</h3>
				<ul class="space-y-2 text-sm">
					<li class="flex items-center">
						<svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
						</svg>
						<a href="tel:{CONTACT_PHONE}" class="hover:text-white dark:hover:text-gray-200 transition-colors duration-300">{CONTACT_PHONE_DISPLAY}</a>
					</li>
					<li class="flex items-center">
						<svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
						</svg>
						<a href="mailto:{EMAIL_ADRESS}" class="hover:text-white dark:hover:text-gray-200 transition-colors duration-300">{EMAIL_ADRESS}</a>
					</li>
				</ul>
			</div>
		</div>

		<!-- Bottom Bar -->
		<div class="border-t border-gray-800 dark:border-gray-900 mt-6 pt-4 text-sm text-center transition-colors duration-300">
			<p><a class="hover:text-white dark:hover-text-gray-200 transtition-colors duration-300" href="/">&copy; {currentYear} IT Hjelperen.</a> Alle rettigheter reservert.</p>
		</div>
	</div>
</footer>

// projects/vehicle-rental-project/components/Footer.tsx
import Link from 'next/link'

export const Footer = () => {
  return (
    <footer className="bg-gray-900 text-white py-12 px-4 md:px-8">
      <div className="max-w-7xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8 md:justify-items-center">
          <div>
            <h4 className="font-bold text-lg mb-4 text-white">Company</h4>
            <ul className="space-y-2 text-sm text-white">
              <li><Link href="/" className="hover:text-primary-500 transition">Home</Link></li>
              <li><Link href="/about" className="hover:text-primary-500 transition">About</Link></li>
              <li><Link href="/our-cars" className="hover:text-primary-500 transition">Our Cars</Link></li>
            </ul>
          </div>
          <div>
            <h4 className="font-bold text-lg mb-4 text-white">Discover</h4>
            <ul className="space-y-2 text-sm text-white">
              <li><Link href="/explore" className="hover:text-primary-500 transition">Explore</Link></li>
              <li><Link href="/location" className="hover:text-primary-500 transition">Location</Link></li>
            </ul>
          </div>
          <div>
            <h4 className="font-bold text-lg mb-4 text-white">Legal</h4>
            <ul className="space-y-2 text-sm text-white">
              <li><Link href="/privacy" className="hover:text-primary-500 transition">Privacy</Link></li>
              <li><Link href="/toc" className="hover:text-primary-500 transition">Terms and Conditions</Link></li>
              <li><Link href="/modify-booking" className="hover:text-primary-500 transition">Modify Booking</Link></li>
            </ul>
          </div>
        </div>
        <div className="border-t border-gray-800 pt-8 text-center text-sm text-white">
          <p>&copy; {new Date().getFullYear()} NorthVenture. All rights reserved. Discover the magic of the Arctic.</p>
          <Link href="/admin" className="mt-2 inline-flex items-center justify-center w-8 h-8 text-gray-600 hover:text-gray-400 transition" aria-label="Admin login">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1" />
            </svg>
          </Link>
        </div>
      </div>
    </footer>
  )
}
